import './Models/Ingredient.dart';

const TYPE_INGREDIENTS = const [
  "Breakfast",
  "MorningBreak",
  "Lunch",
  "AfternoonBreak",
  "Dinner",
  "Extra"
];

const DUMMY_INGREDIENTS = const [
  Ingredient(
      id: 'm1',
      Name: 'Rice',
      Type: 'Main Course',
      KCalxKg: 363,
      CO2xKg: 5,
      WaterxKg: 1575,
      ProteinxKg: 5,
      FatxKg: 1575,
      SugarxKg: 500),
  Ingredient(
      id: 'm2',
      Name: 'Olive Oil',
      Type: 'Water',
      KCalxKg: 900,
      CO2xKg: 6,
      WaterxKg: 318,
      ProteinxKg: 5,
      FatxKg: 1575,
      SugarxKg: 500),
  Ingredient(
      id: 'm3',
      Name: 'Tomatoes',
      Type: 'Dessert',
      KCalxKg: 90,
      CO2xKg: 2,
      WaterxKg: 77,
      ProteinxKg: 5,
      FatxKg: 1575,
      SugarxKg: 500),
  Ingredient(
      id: 'm4',
      Name: 'Coffee',
      Type: 'Dessert',
      KCalxKg: 108,
      CO2xKg: 28,
      WaterxKg: 33,
      ProteinxKg: 5,
      FatxKg: 1575,
      SugarxKg: 500),
  Ingredient(
      id: 'm5',
      Name: 'Eggs',
      Type: 'Dessert',
      KCalxKg: 264,
      CO2xKg: 5,
      WaterxKg: 633,
      ProteinxKg: 5,
      FatxKg: 1575,
      SugarxKg: 500),
  Ingredient(
      id: 'm6',
      Name: 'Fish',
      Type: 'Dessert',
      KCalxKg: 148,
      CO2xKg: 14,
      WaterxKg: 1580,
      ProteinxKg: 5,
      FatxKg: 1575,
      SugarxKg: 500),
  Ingredient(
      id: 'm7',
      Name: 'Bread',
      Type: 'Dessert',
      KCalxKg: 279,
      CO2xKg: 2,
      WaterxKg: 419,
      ProteinxKg: 5,
      FatxKg: 1575,
      SugarxKg: 500),
  Ingredient(
      id: 'm8',
      Name: 'Bovine Meat',
      Type: 'Dessert',
      KCalxKg: 192,
      CO2xKg: 99,
      WaterxKg: 1600,
      ProteinxKg: 5,
      FatxKg: 1575,
      SugarxKg: 500),
  Ingredient(
      id: 'm9',
      Name: 'Cheese',
      Type: 'Dessert',
      KCalxKg: 313,
      CO2xKg: 24,
      WaterxKg: 1560,
      ProteinxKg: 5,
      FatxKg: 1575,
      SugarxKg: 500),
];
